### ISSUE TITLE
Please provide at least a working example in the README

### ISSUE THREAD

**Issue by spectrachrome** [Trangar/artnet_protocol#34]
I would love to use this crate, but it is basically unusable if the example compiles with errors on any library version.

**Comment by TimoteusRuotsalainen** [comment]
Which errors are you getting?

This pull request changed the length field to be calculated internally. The example is wrong regarding this. Length should no longer be supplied manually as it's calculated automatically
https://github.com/Trangar/artnet_protocol/pull/8

**Comment by VictorKoenders** [comment]
I'm not actively maintaining this repository but if someone wants to create a PR to update the example with working code I'll merge it

**Comment by spectrachrome** [comment]
Hi, I'll take a look soon-ish and if I find a fix I'll create a PR with an improved example

**Comment by spectrachrome** [comment]
Yes, it works beautifully now, thank you very much @TimoteusRuotsalainen 😊
Examples for different use cases sound interesting, any specific use cases you have in mind?

**Comment by TimoteusRuotsalainen** [comment]
Somebody asked in another issue about how to receive dmx. I sent a pull request and now we have an example of sending and receiving there. I think answering issues with example code is a good way to help future developers have a good experience.

@VictorKoenders issue resolved. Can close.

**Comment by VictorKoenders** [comment]
Thanks @TimoteusRuotsalainen !
